## **Wilson Mazimba Hoemwork5.**
## 1.  What does Pandas satnd for?
### Pandas stand for panel data as it referneces, both panel data and python data.

## 2. what are the 2 collections used in Pandas
### Pandas primarily uses series and DataFrame as the two main data structures

## 3. Name 4 things Pandas can do for us
### Pandas can do data cleaning, data normalisation, data visualisation and data inspection

## 4. To permanently sort a DataFrame, which keyword should one use with the 'df.sort()' method?
### To permanently sort a DataFrame, we use the 'df.sort()' method with the inplace parameter set to 'True'(inplace = True)

## 5. What is a CSV file?
### A CSV file is a Comma Seperated variables file

## 6. When cleaning data, what values do we not like in our data?
### We dont like NULL values

## **Please Complete this Coding Exercise:**

In [511]:
7. # Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- `.reshape()`
# 7,.(a) 
import numpy as np
arrayA = np.array([2, 3, 2])
print(np.sort(arrayA))



[2 2 3]


In [517]:
# 7. (b) Reshape Method
import numpy as np
arrayA = np.array([2, 2, 3])
New_arrayA = arrayA.reshape(3, 1)
print(arrayA)


[2 2 3]


In [563]:
7. # (c) Reshape arrays - I failed tofix this error, I need help on this one
import numpy as np
int_array1 = np.array('i', [0, 1, 2, 3, 5, 4])
int_array2 = np.array('i', [6, 7, 8, 9, 10, 11])
New_array1 = int_array1.reshape(2, 3)
New_array2 = int_array2.reshape(3, 2)
print(New_array1)
print(New_array2)



<>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
C:\Users\Wilsom Mazimba\AppData\Local\Temp\ipykernel_5484\119056415.py:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
  7. (c) # Reshape arrays


TypeError: 'float' object is not callable

In [522]:
8. # Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20

x = np.linspace(0, 20, num = 6)
print(x)


[ 0.  4.  8. 12. 16. 20.]


In [227]:
9. # Make a Deep Copy of the above array
y = [0., 5. , 10., 15., 20.]
y2 = y.copy()
print(y2)


[0.0, 5.0, 10.0, 15.0, 20.0]


In [65]:
10. # Concatenate these 3 arrays into a new array named 'newArray'
import numpy as np

a = ([[25, 16]])
b = ([[11, 2], [13, 4]])
c = ([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((a, b, c), axis = 0)
print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [70]:
11. # Sort 'newArray' in order into 'sortedArray'
sortedArray = np.sort(newArray)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [537]:
12. # Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.
#i. Variables less than 5
import numpy as np
c = [16, 25, 2, 11, 4, 13, 7, 81, 5, 6, 11, 12]
for num in c:
  if num < 5:
    print(num)



2
4


In [538]:
# ii. Variables greater than 5
c = [16, 25, 2, 11, 4, 13, 7, 81, 5, 6, 11, 12]
for num in c:
  if num > 5:
    print(num)


16
25
11
13
7
81
6
11
12


In [542]:
# iii. Variables divisible by 2
c = [16, 25, 2, 11, 4, 13, 7, 81, 5, 6, 11, 12]
for num in c:
  if num %2 == 0:
    print(num)




16
2
4
6
12


In [89]:
d = c[(c > 25) & (c < 85)]
print(c)

TypeError: '>' not supported between instances of 'list' and 'int'

In [91]:
13. i.# Combined and sort the following arrays into one called 'comboArray'
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
comboArray = np.concatenate((one, two, three), axis = 0)
print(comboArray)

[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]


In [92]:
# 13.ii. sort comboArray
sortecomboArray = np.sort(comboArray)
print(sortecomboArray)


[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [526]:
14. #. Take 'comboArray' and perform the following slicing activities:
# 14. i. Variables less than 5
comboArray = (9, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27, 0, 1, 2, 3, 4, 5, 6, 7)
for num in comboArray:
    if num < 5:
        print(num)




0
1
2
3
4


In [150]:
#14. ii. All elements from the 4th to the 14th elements

comboArray = (9, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27, 0, 1, 2, 3, 4, 5, 6, 7)
print(comboArray[4: 14])

(13, 14, 15, 16, 17, 20, 21, 22, 23, 24)


In [162]:
#14, iii. The last 6 elements
comboArray = (9, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27, 0, 1, 2, 3, 4, 5, 6, 7)
print(comboArray[19 : 25])

(2, 3, 4, 5, 6, 7)


In [180]:
#14. iv. All element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
comboArray = (9, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27, 0, 1, 2, 3, 4, 5, 6, 7)
print(comboArray[-22:])
print(comboArray[-18:])
print(comboArray[-12:])
print(comboArray[-12])
print(comboArray[-9:])

(12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27, 0, 1, 2, 3, 4, 5, 6, 7)
(16, 17, 20, 21, 22, 23, 24, 25, 26, 27, 0, 1, 2, 3, 4, 5, 6, 7)
(24, 25, 26, 27, 0, 1, 2, 3, 4, 5, 6, 7)
24
(27, 0, 1, 2, 3, 4, 5, 6, 7)


In [545]:
#14. v(a).  From #20 every even element to the end
comboArray = (9, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27, 0, 1, 2, 3, 4, 5, 6, 7)
print("\nSlicing from index comboArray[9:] to the end")
print(comboArray[9:])



Slicing from index comboArray[9:] to the end
(20, 21, 22, 23, 24, 25, 26, 27, 0, 1, 2, 3, 4, 5, 6, 7)


In [273]:
#14. v(b) Removing the second line function does not print the comboArray output.
comboArray = (9, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27, 0, 1, 2, 3, 4, 5, 6, 7)
print("\nSlicing from index comboArray[9:] to the end")
print(comboArray[9:])


Slicing from index comboArray[9:] to the end
(20, 21, 22, 23, 24, 25, 26, 27, 0, 1, 2, 3, 4, 5, 6, 7)


In [546]:
#14, vi. From the last element moving forward, every 5th element 
comboArray = (9, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27, 0, 1, 2, 3, 4, 5, 6, 7)
for i in range(0, len(comboArray), 5):
    print(comboArray[i])

9
14
21
26
3


In [308]:
15. # Using `Series`, create a `DataFrame` that looks like this:

    | Ingredients | Quantity | Unit |
    |----|----|----|
    | Flour | 4 | cups |
    | Milk | 1 | cup |
    | Eggs | 2 | large |
    | Spam | 1 | can |

    Name: Dinner, dtype: object


In [341]:
#15 (a) Create the series

import pandas as pd

Ingredients = pd.Series(["Flour", "Milk", "Eggs", "spam"])
Quantity = pd.Series(["Cup", "Cup", "Large", "can"])
Units = pd.Series([4, 1, 2, 1])
print(Ingredients)
print(Quantity)
print(Units)


0    Flour
1     Milk
2     Eggs
3     spam
dtype: object
0      Cup
1      Cup
2    Large
3      can
dtype: object
0    4
1    1
2    2
3    1
dtype: int64


In [340]:
# 15 (b) generate dataFrame

df = pd.concat([Ingredients, Units, Quantity], axis=1)
print(df)

       0  1      2
0  Flour  4    Cup
1   Milk  1    Cup
2   Eggs  2  Large
3   spam  1    can


In [389]:
16. # Take this data and create a DataFrame named studentData
# 16 (a) Create a dictionary

studentData  = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
# 16 ((b) Convert Dictionary to dataFrame)
studentData = pd.DataFrame(studentData)
print("studentData as DataFrame ...\n", studentData)

studentData as DataFrame ...
       Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [421]:
17. # Add a new column to the DataFrame with the following deserts:["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
# Only the new column was printed instead of all the columns, why?
studentData  = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
df['Flavours'] = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
df = pd.DataFrame({'Flavours': ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]})
print(df)

       Flavours
0     ice cream
1  Cashew Fudge
2       waffels
3  Carrot Halwa


In [458]:
# 18. (a) Sort the dataFrame in ascending order - by Name

# creating and initializing a nested list (country, year, population, continent)
studentData  = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
df.sort_values(by = ['Name'], inplace = True)
sorted_dataFrame = df.sort_values(by = 'Name')
print(sorted_dataFrame)

      Name  Height Qualification  address  Age        Pets spot
3     Anuj     5.2           Msc   Dakhar   21      Parrot  NaN
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  NaN
0      Jai     5.1           Msc    Delhi   21         Dog  NaN
1  janusha     6.2            MA     Doha   23       Bunny  NaN


In [459]:
# 18. (b) Sort the dataFrame in ascending order - by Height
studentData  = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
df.sort_values(by = ['Height'], inplace = True)
sorted_dataFrame = df.sort_values(by = 'Height')
print(sorted_dataFrame)

      Name  Height Qualification  address  Age        Pets spot
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  NaN
0      Jai     5.1           Msc    Delhi   21         Dog  NaN
3     Anuj     5.2           Msc   Dakhar   21      Parrot  NaN
1  janusha     6.2            MA     Doha   23       Bunny  NaN


In [460]:
# 18. (c) Sort the dataFrame in ascending order - by Age
studentData  = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
df.sort_values(by = ['Age'], inplace = True)
sorted_dataFrame = df.sort_values(by = 'Age')
print(sorted_dataFrame)

      Name  Height Qualification  address  Age        Pets spot
0      Jai     5.1           Msc    Delhi   21         Dog  NaN
3     Anuj     5.2           Msc   Dakhar   21      Parrot  NaN
1  janusha     6.2            MA     Doha   23       Bunny  NaN
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  NaN


In [496]:
19. # Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`: python
# df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

cows_and_goats = ({'Cows': [12, 20], 'Goats': [22, 19]})
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
print(df)
df.to_csv('cows_and_goats', index = False)

        Cows  Goats
Year 1    12     22
Year 2    20     19


In [497]:

20. # (A) Using Pandas, make your own .CSV file with data on vegetables and save it. 

Veg_Type = ({'cabbage': [10, 20, 15, 19], 'Kale': [14, 12, 20, 55], 'Okra': [53, 63, 77, 99]})
df = pd.DataFrame({'cabbage': [10, 20, 15, 19], 'Kale': [14, 12, 20, 55], 'Okra': [53, 63, 77, 99]}, index=['Year 1', 'Year 2', 'Year 3', 'Year 4'])
print(df)
df.to_csv('Veg_Type', index = False)

        cabbage  Kale  Okra
Year 1       10    14    53
Year 2       20    12    63
Year 3       15    20    77
Year 4       19    55    99


In [501]:
# (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.
New_Veg_Type = ({'cabbage': [150, 210, 152, 195, 200, 369, 699, 754, 765, 870], 'Kale': [144, 123, 206, 553, 376, 324, 543, 765, 243, 546,], 'Okra': [533, 634, 772, 996, 543, 654, 753, 8962, 987,999 ]})
df = pd.DataFrame({'cabbage': [150, 210, 152, 195, 200, 369, 699, 754, 765, 870], 'Kale': [144, 123, 206, 553, 376, 324, 543, 765, 243, 546,], 'Okra': [533, 634, 772, 996, 543, 654, 753, 8962, 987,999 ]}, index=['Year 1', 'Year 2', 'Year 3', 'Year 4', 'Year 5', 'Year 6', 'Year 7', 'Year 8', 'Year 9', 'Year 10'])
print(df)
df.to_csv('New_Veg_Type', index = False)

         cabbage  Kale  Okra
Year 1       150   144   533
Year 2       210   123   634
Year 3       152   206   772
Year 4       195   553   996
Year 5       200   376   543
Year 6       369   324   654
Year 7       699   543   753
Year 8       754   765  8962
Year 9       765   243   987
Year 10      870   546   999
